name: news-classifier-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      # MLflow with Databricks connectivity
      - mlflow[databricks]>=3.1

      # Environment management
      - python-dotenv>=1.0.0

      # LLM providers
      - openai>=1.0.0
      - anthropic>=0.25.0

      # Databricks SDK
      - databricks-sdk>=0.18.0

      # Data handling
      - pandas>=2.0.0
      - numpy>=1.24.0

      # Utilities
      - pydantic>=2.0.0
      - tenacity>=8.2.0

      # ML metrics
      - scikit-learn>=1.3.0

      # Jupyter for notebooks
      - jupyterlab>=4.0.0
      - ipykernel>=6.25.0
      - notebook>=7.0.0

      # Visualization (for EDA notebooks)
      - matplotlib>=3.7.0
      - seaborn>=0.12.0